export enum MediaDetailsEventType {
  DETAILS_LOADING = 'DETAILS_LOADING',
  DETAILS_READY = 'DETAILS_READY',
  DETAILS_UPDATED = 'DETAILS_UPDATED',
  DETAILS_FAILED = 'DETAILS_FAILED',
  ARTWORK_READY = 'ARTWORK_READY',
  SEASON_CHANGED = 'SEASON_CHANGED',
  EPISODE_SELECTED = 'EPISODE_SELECTED',
}
